name: Exercise3

on:
  push:
    branches:
      - main

env:
  MAVEN_OPTS: "-Dmaven.repo.local=./.m2/repository"

jobs:
  oneJobIsAllItTakes:
    name: oneJob
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'oracle'

      - name: Build
        run: mvn compile

      - name: Archive
        uses: actions/upload-artifact@v3
        with:
          name: ${{ github.job }}-artifacts
          path: target/*

      - name: Test
        run: mvn test

      - name: Package
        run: mvn package

  Deploy:
    name: Deploy
    runs-on: self-hosted
    needs: oneJobIsAllItTakes
    steps:
        run: |
         cp ./target/game2048.war /usr/local/tomcat/webapps